services:
  frontend:
    image: hjcasayas/trustworthy-app-download-frontend:v1.0.1
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      args:
        NEXT_PUBLIC_STRAPI_URL: ${NEXT_PUBLIC_STRAPI_URL}
      tags:
        - hjcasayas/trustworthy-app-download-frontend:latest
        - hjcasayas/trustworthy-app-download-frontend:v1.0.1
      platforms:
        - linux/amd64
  cms:
    image: hjcasayas/trustworthy-app-download-cms:v1.0.1
    build:
      context: .
      dockerfile: ./apps/cms/Dockerfile
      tags:
        - hjcasayas/trustworthy-app-download-cms:latest
        - hjcasayas/trustworthy-app-download-cms:v1.0.1
      platforms:
        - linux/amd64
