services:
  dev-container:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../:/workspaces/trustworthy-app-download:cached
      - node_modules:/workspaces/trustworthy-app-download/node_modules
      - pnpm-store:/workspaces/trustworthy-app-download/.pnpm-store
      - next:/workspaces/trustworthy-app-download/apps/frontend/.next
      - dist:/workspaces/trustworthy-app-download/apps/cms/dist
      - strapi:/workspaces/trustworthy-app-download/apps/cms/.strapi
      - types:/workspaces/trustworthy-app-download/apps/cms/types
      - frontend-node_modules:/workspaces/trustworthy-app-download/apps/frontend/node_modules
      - cms-node_modules:/workspaces/trustworthy-app-download/apps/cms/node_modules
    command: sleep infinity
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    build:
      dockerfile: ./apps/frontend/Dockerfile
      context: ../
      target: development
    volumes:
      - ../:/app
      - node_modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store
      - frontend-node_modules:/app/apps/frontend/node_modules
      - frontend-next:/app/apps/frontend/.next
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - cms
    env_file:
      - ./.env
  cms:
    build:
      dockerfile: ./apps/cms/Dockerfile
      context: ../
      target: development
    volumes:
      - ../:/app
      - node_modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store
      - cms-node_modules:/app/apps/cms/node_modules
      - cms-dist:/app/apps/cms/dist
      - cms-strapi:/app/apps/cms/.strapi
      - cms-types:/app/apps/cms/types
    restart: always
    ports:
      - 1337:1337
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  node_modules:
  pnpm-store:
  next:
  dist:
  strapi:
  types:
  frontend-node_modules:
  frontend-next:
  cms-node_modules:
  cms-dist:
  cms-strapi:
  cms-types:
  postgres-data:
