services:
  dev-container:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../:/workspaces/trustworthy-app-download:cached
      - node_modules:/workspaces/trustworthy-app-download/node_modules
    command: sleep infinity
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  node_modules:
  postgres-data:
