services:
  dev-container:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../:/workspaces/trustworthy-app-download:cached
      - node_modules:/workspaces/trustworthy-app-download/node_modules
      - pnpm-store:/workspaces/trustworthy-app-download/.pnpm-store
      - next:/workspaces/trustworthy-app-download/apps/frontend/.next
      - frontend-node_modules:/workspaces/trustworthy-app-download/apps/frontend/node_modules
    command: sleep infinity
  frontend:
    build:
      dockerfile: ./apps/frontend/Dockerfile
      context: ../
      target: development
    volumes:
      - ../:/app
      - node_modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store
      - frontend-node_modules:/app/apps/frontend/node_modules
      - frontend-next:/app/apps/frontend/.next
    restart: always
    ports:
      - 3000:3000
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  node_modules:
  pnpm-store:
  next:
  frontend-node_modules:
  frontend-next:
  postgres-data:
