name: Build and Push Images to Docker Hub

on:
  push:
    branches: ["master"]
    paths:
      - "docker-compose.build.yaml"
  workflow_dispatch:

jobs:
  production-build-and-push:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_STRAPI_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Build the Docker image
        run: pnpm run docker:build
      - name: Push the Docker image
        run: |
          docker login -u hjcasayas -p ${{ secrets.DOCKER_HUB_TOKEN }}
          pnpm run docker:push
